### ISSUE TITLE
Feature request and question

### ISSUE THREAD

**Issue by FunkeyMonkey** [courtneypattison/betrayal-dice#1]
Hello! Started testing the app and really loving the omen roll part. 

1. First to the request, like the probabilities toggle, it would be nice to have an option to toggle seeing the actual dice rolled instead of just the number. I think this is the only reason i haven't fully switched over to yours permanently.

![image](https://user-images.githubusercontent.com/13045972/123159231-0276ff00-d42a-11eb-9d09-81aa7c155516.png)

2. For the question, i'm having a little trouble understanding the rolls when doing an attack. What are the small numbers on the outside of the large numbers?

![image](https://user-images.githubusercontent.com/13045972/123158871-8bda0180-d429-11eb-9136-9c75c7bba900.png)

**Comment by courtneypattison** [comment]
@FunkeyMonkey Thank you for the feedback! I like the idea of toggling the actual dice rolled. Any ideas for where to put the toggle option? I could probably just put the values above ROLL and ATTACK. The small numbers on the outside are the previous roll values. I put them there because sometimes I need to know what I rolled last and I'm forgetful! Any ideas for how to make that more obvious? Maybe I should add a toggle for showing the previous roll values and actual dice rolled in the settings. Thank you again :)

**Comment by FunkeyMonkey** [comment]
Oh duh haha that makes total sense now. For the dice toggle I’d suggest right below Probabilities. There’s tons of space there for options.  For the rolls, I had a couple ideas. Either list them below the dice counter/above the outcome toggle or maybe as part of the dice toggle, you could have that do a popup just like the Haunt roll. With the show dice option checked then any roll or attack would just popup on the screen like in the picture I had sent. Just an idea on that, I’m sure you can come up with something more creative there lol. For the prev roll, maybe in the settings menu or a little Help button above New Game, it could either turn on an overlay that would highlight some of the key items/numbers on the screen or it could open a picture of everything activated with little text as a how-to kinda thing. Last thing I wanted to bring up, I’ve noticed twice now when doing the haunt roll that it’s not triggered a haunt as you can see in the picture. The other time I believe it rolled a 4 and was on omen 5. Thanks for listening to my rambling!  On Wed, Jun 23, 2021, 6:14 PM Courtney Pattison ***@***.***> wrote:@FunkeyMonkey Thank you for the feedback! I like the idea of toggling the actual dice rolled. Any ideas for where to put the toggle option? I could probably just put the values above ROLL and ATTACK. The small numbers on the outside are the previous roll values. I put them there because sometimes I need to know what I rolled last and I'm forgetful! Any ideas for how to make that more obvious? Maybe I should add a toggle for showing the previous roll values and actual dice rolled in the settings. Thank you again :)—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by courtneypattison** [comment]
@FunkeyMonkey Thank you again for all the ideas! I'll see what I can come up with tomorrow. I'll look into the haunt roll not starting as well. In your settings, do you have the 'Original' setting enabled or one of the others? For 'Legacy' the haunt only starts on 6+ and for 'Unofficial' it only starts on 7+. I may have messed up the default to be one of those two. I'm just making guesses. I'll know better when I look into it tomorrow. Please let me know if you have any more issues!

**Comment by FunkeyMonkey** [comment]
My pleasure! I did check the settings and it's on original. That must be
default as I don't recall changing that.

**Comment by courtneypattison** [comment]
Ok, thank you! I'll let you know when I have more information :)

**Comment by FunkeyMonkey** [comment]
Sounds good!

**Comment by courtneypattison** [comment]
@FunkeyMonkey I fixed the haunt roll not starting and pushed a new release with the fix. It was a pretty embarrassing bug that I introduced when adding the haunt roll settings. Apologies for the app being unreliable :( On a happier note, I've started the toggle for the actual dice rolled. I like your idea of putting it below the roll outcome probabilities, so I'm starting with that. Thank you again for the help! Please let me know if I've muddled anything else up with the latest release.

**Comment by FunkeyMonkey** [comment]
Awesome! I'll be sure to grab th new version. Doing a betrayal game night
Saturday so I'll have lots of testing done haha

**Comment by courtneypattison** [comment]
@FunkeyMonkey I finally added the dice values option to the app in v1.4! Please let me know if you have any problems with it or suggestions to make it better. For making the previous roll/attack values more obvious, I haven't decided what I want to do for that yet, so as a temporary help, I put a screenshot in the main listing for the app with arrows pointing to the values and a brief description. Thank you again for all your help on this! The app has definitely improved thanks to you :)

**Comment by FunkeyMonkey** [comment]
Sweet!! I'm super excited to test out the roll option. I suggested it kinda
on a whim but after playing a couple times since, it's definitely a must
for those cards that allow you to reroll X number of dice. Now we can see
how many were 0s etc and keep it accurate.

I'll let you know how it goes!

**Comment by courtneypattison** [comment]
Ahh, I forgot about those! I haven't been able to play Betrayal since the pandemic hit, so I definitely miss the game and haven't had the chance to test the app that thoroughly.

**Comment by FunkeyMonkey** [comment]
No worries! I'll get plenty of testing in for ya!

**Comment by FunkeyMonkey** [comment]
One little thing I noticed with the update, looks like the layout shifted
just a tad on the left and runs off the screen.

Also a suggestion to tweak the rolled dice number locations. Might be tad
easier to read if they were spaced little on left and right. Pardon my
crude drawing on my phone as an example lol

**Comment by courtneypattison** [comment]
Thank you! I think I fixed the shifted layout. I accidentally sized it to my screen, so I didn't notice. I couldn't see an image attached to your last message. Do you mean something like this image, where there is more padding between the individual dice values? Thank you again for all your help!

![Screenshot_20210716-143954](https://user-images.githubusercontent.com/5465100/125994289-f985eb7a-6914-4dda-b713-735e2b4ba399.png)

**Comment by FunkeyMonkey** [comment]
Hehe all good. For the roll numbers, I was thinking th attack ones to the
right of the roll ones, so it's kinda formatted same as when you get your
numbers up top

**Comment by courtneypattison** [comment]
Oooh, I like that idea. Something like this?

![Screenshot_20210716-151635](https://user-images.githubusercontent.com/5465100/125998067-7b27b0e0-c0e5-4c9e-b3b7-ed9082a2270b.png)

**Comment by FunkeyMonkey** [comment]
Yeah! I think that makes it a lot easier to read.

Only other suggestion I can think of is for the haunt roll. Love how the
rolling works, but when the haunt happens the omen number disappears. Not a
huge deal as I can count the cards but might be nice to leave the number
there when it switches over.

Keep up the great work!!!

**Comment by courtneypattison** [comment]
Another excellent suggestion! Even just with testing, I was getting annoyed with the omen card count disappearing, but I was being lazy and ignored it. I just started the release rollout with your suggestions. Version 1.5 should be available in an hour or so.

**Comment by FunkeyMonkey** [comment]
Haha glad I could motivate ya 😂 I'll check it out soon as it's up. Thanks,
have a great rest of your weekend!

**Comment by courtneypattison** [comment]
Thanks, you too!
